- hosts: web_servers
  gather_facts: no
  tasks:
    - name: Ping servers
      ansible.builtin.ping:

    - name: Ensure Nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present
