- hosts: web_servers
  gather_facts: no
  tasks:
    - name: Test connectivity
      ansible.builtin.ping:

    - name: Install htop for testing
      ansible.builtin.package:
        name: htop
        state: present
      become: true
